### PR TITLE
Gulp

### PR DESCRIPTION
**Pull request by connorwyatt**
I've created the Gulp setup, information on how to download dependencies etc. are in the contributing section of the readme.

I have minified your SVGs as well and this is built into the Gulp setup so any new SVGs will be minified automatically for you.

Let me know if there is anything else to add to this, I'd like to support the project as it is very good. :)

Thanks

### CODE REVIEW

**Comment by connorwyatt** [comment]
By the way the CSS prefixes are not the same as I'm not sure what prefixer settings you were using but if you want to change them that's fine by me

**Comment by dbox** [comment]
Awesome. Thanks! I'll look into this this weekend.

**Comment by connorwyatt** [comment]
The commits I just added remove bourbon and add some stuff into the readme, but the last commit is just a linted version of the SCSS files, feel free to ignore that one if you're not bothered about that.

The reason I did it is because you won't need the vendor prefixes if you set up autoprefixer.

Your choice :)

**Comment by dbox** [comment]
This is great, and the gulp rendering is instantaneous! I'll get this all in. Thanks!

**Comment by connorwyatt** [comment]
Yeah it is really quick and the browser sync plugin is quick too!

Works great when CSS coding is what you’re doing :)

**Pull request merged**
