### PR TITLE
Better calc detection & fallback, code optimisations & cleanup

### PR DESCRIPTION
**Pull request by IanCaunce**
Changes
 - Added better calc detection
 - Added fallback support for any browser which doesn't natively support calc. (Mainly needed for android 3+ & 12.x opera)
 - Various code optimisations such as removing unnecessary creation of jQuery objects & node caching.
 - Code clean up by re-writing parts to the most common style in the file & removal of unnecessary comments.
 - Replaced the ; with a + on the self executing function as some minifiers strip the first one out.
 - Added a ! to the first comment to prevent minifiers from stripping it out by default.

I apologise in advance if I was meant to create separate pull requests for these changes. This is my first on github.

Commit:  4d9a3a8
For some unknown reason, when the parent element to the rrssb-buttons element has a percentage padding left & right, with the calc polyfill in place and the child elements widths add up to that of the parent, the last element will wrap to a newline. The 1px saftey net sorts that issue out.

Edit: The issue was caused by browsers rounding fractional pixel widths to the nearest whole pixel. This means you can end up in a situation where the width of the element is reported to be larger than it actually is. The only consistent way I can see is to - 1 off the width given. You can get the fractional width by using $('.something')[0].getBoundingClientRect().width but unfortunately .width is undefined in <= IE8.

### CODE REVIEW

**Comment by dbox** [comment]
Added to dev branch. will be pushed with next release. thanks!

**Comment by dbox** [comment]
Would you mind resubmitting this to the dev branch? Thanks!

**Comment by dbox** [comment]
@aicarlson Want to look at this and see if you can get it merged cleanly into latest?

**Comment by aicarlson** [comment]
@dbox Sure, I'll take a look later tonight.

**Comment by IanCaunce** [comment]
@dbox Done. Pull Request #89

**Pull request merged**
