### PR TITLE
Add Telegram button (All fixed, CC #171)

### PR DESCRIPTION
**Pull request by Stichoza**
Fixed everything that was incorrect in #171. Everything works as it should.

### CODE REVIEW

**Comment by Stichoza** [comment]
### Preview

screen shot 2017-04-09 at 12 35 37
screen shot 2017-04-09 at 12 35 58
screen shot 2017-04-09 at 12 37 09
screen shot 2017-04-09 at 12 38 01

**Comment by dbox** [comment]
Is it just me or does the airplane not look visually centered?

**Comment by Stichoza** [comment]
It's taken from Telegram's official logo.

I captured a GIF - One frame is [official logo](https://telegram.org/img/t_logo.png), second is SVG provided in this package and the third frame is moth of them combined. (I changed the tint of official logo to easily see difference)

**Comment by Stichoza** [comment]
Any updates on this?

**Pull request closed without merging**
