### PR TITLE
Small refactorings, performance enhancement and delicious button

### PR DESCRIPTION
**Pull request by czerasz**
I added a `Gruntfile.js` which makes development easier.
It also adds support for [autoprefixer](https://github.com/nDmitry/grunt-autoprefixer) and SVG sprites which enables browser caching.

### CODE REVIEW

**Comment by dbox** [comment]
Cool. We'll look this over. We definitely don't want to have to require Ruby or Node, but having grunt support is great. 

Thanks for contributing!

**Comment by czerasz** [comment]
Hi @dbox,

Made an [additional small change](https://github.com/czerasz/rrssb/commit/54f0482a5587bac4320301f2dd39faaf7fc226f3). Maybe we can take it with this pull request.

**Comment by dbox** [comment]
Can you resolve the conflicts and resubmit? Thanks!

**Comment by czerasz** [comment]
Synced my `feature/delicious` with your recent `master` changes.

**Comment by czerasz** [comment]
Hi,

Sorry for the late response.

Good question. I don't think you can edit the `img/icons.svg` with Illustrator because it contains only symbols.

Tried to goggle for "Illustrator import svg symbol" and also checked in the Illustrator's symbol panel but didn't find anything :-(.

But there is hope. One could add `xmlns:xlink="http://www.w3.org/1999/xlink"` to the svg header tag. And then also add `<use>` tags with `0` opacity. 

Example below:

    <use xlink:href="#icon-linkedin" opacity="0"/>

This will allow You to preview the svg in Illustrator. I'm not sure what happens after you save it.

**Comment by IanCaunce** [comment]
It's also worth noting that using an svg spritesheet like this isn't supported in any version of Internet Explorer or Android 3.0 - 4.3

There is a polyfill for IE but not for Android.

https://github.com/jonathantneal/svg4everybody

**Comment by IanCaunce** [comment]
Also with regards to illustrator, would the correct workflow be: edit the individual svg's and use the grunt task to recreate the icons.svg spritesheet rather than editing it directly

**Comment by dbox** [comment]
Hi @czerasz. We decided to go with gulp instead of grunt, but I was able to add your delicious button. Pull down the latest and check it all out. I think this will be better fit your workflow now. Thanks again!

**Comment by czerasz** [comment]
Looks great. Well done!

**Pull request closed without merging**
