### PR TITLE
Email insta

### PR DESCRIPTION
**Pull request by dbox**
- takes care of number #176
- introduces a replacement icon for the mail icon. Previously it was an "@" symbol, but people have complained that it can be confused for Twitter. The original at-symbol can still be copied over from the icons folder if someone needs it. Screenshot here: 
image

- updates all site references to http://rrssb.ml

### CODE REVIEW

**Comment by dbox** [comment]
@gquemener fixed in 1.13.0. sorry about that!

**Comment by dbox** [comment]
Also I"m not sure how you could be seeing the buttons like that, regardless of the border appearing..

**Comment by gquemener** [comment]
Hello @dbox, I've just updated and the problem is still here. I'm importing the css file (in rrssb/css/rrssb.css) which still contains the border statement, something went wrong in your build process?

I'm not sure why the buttons are displayed like that also, I'm investigating.
Does the width of the buttons is calculated through javascript or is it a full-css behaviour?

**Comment by dbox** [comment]
> Hello @dbox, I've just updated to 1.13.0 and the problem is still here. I'm importing the css file (in rrssb/css/rrssb.css) which still contains the border statement, something went wrong in your build process?

Looks like the minified css didn't get pushed. Try now please.

> Does the width of the buttons is calculated through javascript or is it a full-css behaviour?

Both

**Comment by gquemener** [comment]
I think I understand.

The buttons are not present in the dom on first load (on document ready event), so I have to manually call the `window.rrssbInit()` function when I add them.

**Comment by gquemener** [comment]
> Looks like the minified css didn't get pushed. Try now please.

Great, the border is not here anymore on 1.13.1.

Thanks for your lib :wink: :+1:

**Pull request merged**
