### PR TITLE
Add print option.

### PR DESCRIPTION
**Pull request by froboy**
Client wanted a print button. We loved RRSSB and so I thought I'd try and give back. 

Print icon is via <a href="https://design.google.com/icons/#ic_print">Google's Material Design Guide</a>. I had some issues with the SVG since it's two paths and I couldn't reliably squish it into one, so there's an ugly line of CSS at the end of the file to override the styles for this icon. If anyone can point me to a better SVG, I'm happy to replace it. 

I was kinda grumpy at the client for demanding a print button in 20-f-ing-16, so I used a <a href="http://www.pdp8.net/images/greenbar.shtml">color inspired by the golden age of printing</a>.

### CODE REVIEW

**Comment by dbox** [comment]
Nice! Thnx. Mind posting a screenshot? (Not able to run the build atm)

**Comment by froboy** [comment]
ridiculously_responsive_social_sharing_buttons_by_kni_labs_and_ridiculously_responsive_social_sharing_buttons_by_kni_labs

**Comment by dbox** [comment]
Ha. cool. I'd probably go with a medium gray or cool gray, but I dig it. We
can get this in.

**Comment by froboy** [comment]
Yea, I thought the palette could use a little green, but looking at it more it definitely doesn't quite fit in. Doubt the client will go for my rage-green anyway... How's "dead-tree charcoal"?

**Comment by dbox** [comment]
image

**Comment by froboy** [comment]
Works for me...

**Comment by dbox** [comment]
Thanks @froboy! :ship: :tada:

**Pull request merged**
