### PR TITLE
Update index.html to match SVG changes

### PR DESCRIPTION
**Pull request by AdamPS**
For issue #130

### CODE REVIEW

**Comment by AdamPS** [comment]
Sorry I'm just learning git.  OK, so it seems this pull request now has my second fix in it automatically.  The second one is for #133 and is more complex, I feel potentially very useful, but possibly controversial / wrong:-)  So please review carefully before merging.

**Comment by dbox** [comment]
I'm happy to take the index as a PR but the other one really messes with the icon and font sizing..

**Comment by AdamPS** [comment]
True, sorry about that.  If I can tweak the numbers and get it a closer in appearance to before, would you be interested?  It does solve a bug or two as well as being more compact CSS.

Or is this perhaps the point where I should fork?  I'm trying to delay that as I feel the more code we have in common the better for long term ease of maintenance.  But I'm not going to bang my head against a brick wall about it.

**Comment by dbox** [comment]
Yeah, happy to look at it again if you can get it looking exactly 1-to-1, but for now this is very far off.

**Comment by dbox** [comment]
If you can remove the last commit, I'll get the index merged up at least.

**Comment by AdamPS** [comment]
OK, I have reverted the last commit, thanks.

**Comment by dbox** [comment]
Can you just prune those last 2 commits off? Or I can just bring in the index on its own not in a PR. Thanks!

**Comment by AdamPS** [comment]
OK, this is stretching my ability with Git, but I think I might have got it.

**Pull request closed without merging**
