### PR TITLE
Added Telegram button

### PR DESCRIPTION
**Pull request by theus**

### CODE REVIEW

**Comment by dbox** [comment]
Hey Theus-

Thanks for contributing! I've personally never heard of Telegram, but if it gets popular enough and enough people want it, I'd be happy to add.

Adding sites adds filesize (albeit very slight) to the css. While this is not an issue when users use the sass file, I'd still like to make sure the default set of sites are widely used.

**Comment by theus** [comment]
@dbox I understand. Telegram is a excellent messenger app and is growing up well. I created the button to add in a project and I decided make a PR :relieved:

**Comment by dbox** [comment]
totally. appreciate it!

**Comment by yguezeldal** [comment]
+1

**Comment by finex** [comment]
+1 to add Telegram support

**Comment by Stichoza** [comment]
Telegram is the number one messenger in Eastern Europe and Asia. Following Whatsapp and Viber.

+999999 for Telegram. Please merge

**Comment by Lotuashvili** [comment]
+1

**Comment by Stichoza** [comment]
@theus The SVG icon you provided doesn't go with other icons. The telegram icon itself has colors in SVG paths instead of simply be cut out.

It should be something like this:
screen shot 2017-04-09 at 12 05 49

You can take a look at Whatsapp icon on a demo page and see how the inner green part of the icon changes on hover.

**Comment by lucacividini** [comment]
Can you merge this features for having the telegram button? thank's to @Stichoza and @theus for this work!

**Pull request closed without merging**
