### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by dbox** [comment]
Not really hurting anything at the moment, plus it future proofs it. The bower file is going to get significally changed in 2.0, but if you really want to have this merged in, resubmit to /dev branch and i'll pull it in.

**Comment by dbox** [comment]
Also, just curious why you are so passionate about this?

https://www.dropbox.com/s/ocwdyftbjjs4ptg/Screenshot%202015-06-10%2020.15.08.png?dl=0

**Comment by kkirsche** [comment]
@dbox mix of reasons. This PR will be going to every single repo that has a bower.json with version in it by the time I'm done.

1. OCD — I hate people wasting time and energy on worthless code.
2. In my opinion bower hurts the community more then helps. It's not a good package manager as far as JS package managers go in my opinion (though it was great for what it was when it was made). The problem is that NPM really has become the defacto JS package manager and Bower does nothing but contribute to fragmentation in the JS community. In my opinion, Bower pushed the community forward but not longer does so. For that reason I would rather see people follow the spec closely so if it does go away as from rumors I've heard then it's one less thing to ditch.

**Comment by dbox** [comment]
Rumors of bower going away?

**Comment by kkirsche** [comment]
That's what I've heard. Whether true or not who knows. Rumors are rumors. But this change mirrors enough major repos or repos which have existing pr's from other devs (things like bootstrap, normalize, etc.) that might as well ensure everyone at least is following the same conventions or at least is aware that they are including a pointless key:value pair.

**Comment by dbox** [comment]
I would like to see any links you have where that is discussed. I can imagine just trying to manage it is a big headache for the project owners.

Do you use all the repo's that you are doing thes PRs for? Do you use RRSSB with bower?

**Comment by kkirsche** [comment]
Nope. I would say I maybe use 3%, if that, of the 27K packages. I've used RRSSB in the past via bower but moved to NPM as I expect it to have longer support. I'll have to look and find the pages, if I find them though I'll def shoot them your way :+1:

**Comment by dbox** [comment]
Well we'd love to setup an npm package for rrssb with version 2 if you'd be willing to help with that.

**Comment by kkirsche** [comment]
Definitely can help with that. Here's a basic gist though which is a great general reference:
https://gist.github.com/coolaj86/1318304

Sorry for the delay in responding. I hit the Issue / PR creation rate limit again... :cry:

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Pull request closed without merging**
