### PR TITLE
Update rrssb.js

### PR DESCRIPTION
**Pull request by aicarlson**
Forgot to add the settings update for the new hackernews button. Also fixed the KNI logo formatting that was broken in the last merge.

### CODE REVIEW

**Comment by aicarlson** [comment]
I know, I know. Just send 1 pull request with all of the updates, not 5 small ones. I just keep looking through the issues and thinking 'Oh, I can get that done.'

**Comment by dbox** [comment]
Just now seeing this. Is this still needing to go in? I just added a ton of stuff..

**Comment by dbox** [comment]
pulled. somehow had to refix it anyway. Be sure to grab all the new stuff.

**Comment by aicarlson** [comment]
Thought I had just forked the newest dev branch but I'll be sure to double check
next time.

On Mon, Apr 13, 2015 at 10:12 PM, kni-labs/rrssb
<reply@reply.github.com>
wrote:pulled. somehow had to refix it anyway. Be sure to grab all the new stuff.

—
Reply to this email directly or view it on GitHub
[https://github.com/kni-labs/rrssb/pull/91#issuecomment-92576376] .[https://github.com/notifications/beacon/AFObZjftDmPLzqMqEpc5rrOTMeP-gMmRks5n_H0CgaJpZM4D_5Zy.gif]

**Comment by dbox** [comment]
Oh, I just mean grab all the stuff i *just* added for future. Did a bunch tonight. Thanks for all the help!

**Pull request merged**
