### PR TITLE
Share counter added

### PR DESCRIPTION
**Pull request by connorwyatt**
The current progress is that the share counter has been added, the icons load via ajax, but the buttons don't yet size.

I was going to modify the code from the original but if you're happy to do the sizing I'll leave it :)

### CODE REVIEW

**Comment by connorwyatt** [comment]
Just realised there is no documentation written for what I've done so far, I'll update the readme when I get chance

**Comment by dbox** [comment]
This is awesome. I like the no-js fallback.

**Comment by connorwyatt** [comment]
Yeah? I'm glad, it wasn't even intentional, I just realised that because it gets cleared before the buttons get added you can use it with no js

**Comment by connorwyatt** [comment]
Nice little accident there!

**Comment by dbox** [comment]
I just pushed to 2.0. Make sure you sync with upstream.  

Also, after playing around with it, I think we leave it as index.html. Works better with the gulp server.

**Comment by connorwyatt** [comment]
I see, I will do.

Also I think I can change the default page that opens with the gulp server, so if you want to change it it won’t be a problem

**Pull request merged**
