### PR TITLE
Jsmoriss master

### PR DESCRIPTION
**Pull request by dbox**

### CODE REVIEW

**Comment by dbox** [comment]
@connorwyatt Any idea why these few icons always get re-minified each time?

**Comment by connorwyatt** [comment]
@dbox I wrote it that ways as a good build process should build all files each time. It would be no good if the icons needed to be manually minified after changes had  been made.

**Comment by dbox** [comment]
Oh yeah I know.  These specific ones just seem to change no matter what. They haven't been touched.

**Comment by connorwyatt** [comment]
I see, maybe we're using different versions of the svg minifier? I would still expect it to be stable though :/

**Pull request merged**
